/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int FLOAT = 7;
  /** RegularExpression Id. */
  int BOOL = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int ACHAVES = 11;
  /** RegularExpression Id. */
  int FCHAVES = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int PV = 14;
  /** RegularExpression Id. */
  int ATRIB = 15;
  /** RegularExpression Id. */
  int V = 16;
  /** RegularExpression Id. */
  int SOMA = 17;
  /** RegularExpression Id. */
  int SUB = 18;
  /** RegularExpression Id. */
  int MULT = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int LESSER = 23;
  /** RegularExpression Id. */
  int GREATER = 24;
  /** RegularExpression Id. */
  int EQUAL = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int RETURN = 28;
  /** RegularExpression Id. */
  int PRINT = 29;
  /** RegularExpression Id. */
  int TOKEN_id = 30;
  /** RegularExpression Id. */
  int TOKEN_numliteral = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"let\"",
    "\"float\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\";\"",
    "\":=\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"if\"",
    "\"while\"",
    "\"return\"",
    "\"printIO\"",
    "<TOKEN_id>",
    "<TOKEN_numliteral>",
  };

}
